apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-project
  labels:
    app: gitops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-project
  template:
    metadata:
      labels:
        app: gitops-project
    spec:
      containers:
      - name: gitops-project
        image: gitops-project # Kustomize reemplazará esto
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
            requests:
                memory: "64Mi"
                cpu: "50m"
            limits:
                memory: "128Mi"
                cpu: "200m"
